CREATE TABLE IF NOT EXISTS STUDENT (
  JMBAG   VARCHAR(10) PRIMARY KEY,
  NFC_ID  VARCHAR(255) UNIQUE NULL,
  NAME    VARCHAR(50)         NULL,
  SURNAME VARCHAR(100)        NULL,
  EMAIL   VARCHAR(100)        NULL,
  PICTURE BYTEA
);