CREATE TABLE IF NOT EXISTS TICKET(
  STUDENT_JMBAG VARCHAR(10) REFERENCES STUDENT(JMBAG) ON DELETE CASCADE,
  TICKET_TYPE_ID INTEGER REFERENCES TICKET_TYPE(ID) ON DELETE CASCADE,
  BOUGHT_ON TIMESTAMP NULL,
  PRICE FLOAT NULL,
  CONSTRAINT TICKET_PK PRIMARY KEY (STUDENT_JMBAG, TICKET_TYPE_ID)
);