package org.kset.brucx.util;

/**
 * Created by marin on 14.12.2016..
 */
public enum Query {
    GET_TICKET_TYPE_BY_NAME, GET_TICKET_TYPES, GET_TICKET_BY_JMBAG, GET_TICKET_BY_ID, GET_STUDENT_TICKETS, GET_TICKET_TYPE_BY_NAME_TICKETS, GET_TICKET_TYPE_BY_ID_TICKETS, STORE_TICKET, DELETE_TICKET
}
